### PR TITLE
Added pre-existing distro_data

### PR DESCRIPTION
**Pull request by rachejazz**
`distro_list` contains the list of files which needs to be downloaded.
To update the contents of any file, put the <name\>.json into `distro_list` and follow this script to download all json data:
```
while read -r line; do curl -o `echo $line | cut -f 8 -d "/"` $line; done < distro_list
```
Find all the distro data here:
```
┬─[divya at racharch in ~/a/o/s/distro_data]─[G:test1]─[B:31%, 00:20:58 remaining]
╰──> λ ls
distro_list                 RHEL_8_Package_List.json                               SUSE_Package_Hub_SLES_12_SP2.json  Ubuntu_19_04_Package_List.json
RHEL_7_6_Package_List.json  Suse_Linux_Enterprise_Server_12_SP3_Package_List.json  SUSE_Package_Hub_SLES_12_SP3.json  Ubuntu_19_10_Package_List.json
RHEL_7_7_Package_List.json  Suse_Linux_Enterprise_Server_12_SP4_Package_List.json  SUSE_Package_Hub_SLES_12_SP4.json  Ubuntu_20_04_Package_List.json
RHEL_7_8_Package_List.json  Suse_Linux_Enterprise_Server_12_SP5_Package_List.json  SUSE_Package_Hub_SLES_12_SP5.json  Ubuntu_20_10_Package_List.json
RHEL_7_9_Package_List.json  Suse_Linux_Enterprise_Server_15_Package_List.json      SUSE_Package_Hub_SLES_15.json      Ubuntu_21_04_Package_List.json
RHEL_8_1_Package_List.json  Suse_Linux_Enterprise_Server_15_SP1_Package_List.json  SUSE_Package_Hub_SLES_15_SP1.json
RHEL_8_2_Package_List.json  Suse_Linux_Enterprise_Server_15_SP2_Package_List.json  SUSE_Package_Hub_SLES_15_SP2.json
RHEL_8_3_Package_List.json  SUSE_Package_Hub_SLES_12_SP1.json                      Ubuntu_18_04_Package_List.json
```

### CODE REVIEW

**Comment by rachejazz** [comment]
All previous old distro list has been removed. In comparison with PDS, this directory does not have Ubuntu 16,17 list. Rest all is same

Linked PR with issue openmainframeproject/software-discovery-tool#35

**Comment by pleia2** [comment]
Instead of copying this data here in every month when PDS updates it, my vision was that we'd simply document that people should go to PDS directly if they want data for SLES, RHEL, and Ubuntu. Maybe we could include your script to make it easier for people to import the PDS data?

This repository would be used for any data sources we develop within OMP.

**Comment by rachejazz** [comment]
> Instead of copying this data here in every month when PDS updates it, my vision was that we'd simply document that people should go to PDS directly if they want data for SLES, RHEL, and Ubuntu. Maybe we could include your script to make it easier for people to import the PDS data?
> 
> This repository would be used for any data sources we develop within OMP.

Yes ofc, this is the initial entry to this repo. After this, it should be the user who will update it themselves. Will there be absolutely no data at all regarding RHEL/Ubuntu/SLES ?

**Comment by rachejazz** [comment]
This PR template will be same in case we add z/OS, Debian. ClefOS files.
Closing this!

**Pull request closed without merging**
